/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

// The original cloud model, tinted per project. Lit by the theme-aware scene
// lights, so it reads correctly in both dark and light modes.
export function Cloud({ opacity, color = "#ffffff", ...props }) {
  const { nodes, materials } = useGLTF("./models/cloud/model.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry}>
        <meshStandardMaterial
          {...materials["lambert2SG.001"]}
          transparent
          opacity={opacity}
          color={color}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/cloud/model.glb");
